context:
  version: "0.21.0"

package:
  name: pylangacq
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pylangacq/pylangacq-${{ version }}.tar.gz
  sha256: 99f0a93d589b20a379c2c908eddd85bb9a78c12b654bcfabea3a55a8517fc330

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - rustling >=0.5.0

tests:
  - python:
      imports:
        - pylangacq
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://pylangacq.org
  summary: Language Acquisition Research in Python
  license: MIT
  license_file: LICENSE.txt
  documentation: https://pylangacq.org
  repository: https://github.com/jacksonllee/pylangacq

extra:
  recipe-maintainers:
    - jacksonllee
